### ISSUE TITLE
Add License or Explicit Ban

### ISSUE THREAD

**Issue by exoconnor** [reactorcore/eslint-config-hackreactor#2]
Hi!

I find that I'm still using the Hackreactor styleguide personally, with some additions. I'd like to share it with other people on my team as a reasonable starter linter rather than using something heavy like AirBnB. Is that allowable or is this Hackreactor secret sauce?

...I guess it's in our project repos which are open-sourced with permissive license, but I don't want to bypass anything.

**Comment by fredx** [comment]
Hi @techacolyte42 this repo is licensed under the MIT OS license.
